- platform: zoneminder
  include_archived: false
- platform: time_date
  display_options:
    - 'time'
- platform: template
  sensors:
    external_url: 
      value_template: !secret external_url
    in_temp:
      friendly_name: "Temperatura"
      unit_of_measurement: '°C'
      value_template: "{{states.climate.aire_acond_habitacion.attributes.current_temperature}}"
    door_sensor_battery:
      friendly_name: "Batería Sensor Puerta"
      unit_of_measurement: '%'
      value_template: "{{states.binary_sensor.wyzesense_779015eb.attributes.battery_level}}"
    motion_sensor_battery:
      friendly_name: "Batería Sensor Movimiento"
      unit_of_measurement: '%'
      value_template: "{{states.binary_sensor.wyzesense_778f946a.attributes.battery_level}}"
    doorbell_sensor_battery:
      friendly_name: "Batería Sensor Timbre"
      unit_of_measurement: '%'
      value_template: "{{states.binary_sensor.wyzesense.attributes.battery_level}}"
    ac_energy_value:
      friendly_name: "Consumo de energía AC"
      unit_of_measurement: 'Wh'
      value_template: "{{states.climate.aire_acond_habitacion.attributes.power_consumption_energy}}"
    ac_energy_value_kwh:
      friendly_name: "Consumo de energía AC en kwH"
      unit_of_measurement: 'kWh'
      value_template: "{{states.climate.aire_acond_habitacion.attributes.power_consumption_energy / 1000}}"
    despertador_brenda:
      friendly_name: "Despertador cel Brenda"
      value_template: >
        {% if is_state('sensor.sm_g9650_2_next_alarm', 'unavailable') %}
        {{ 4102444800 | timestamp_local }}
        {% else %}
        {{ states('sensor.sm_g9650_2_next_alarm') }}
        {% endif %}
    despertador_pepe:
      friendly_name: "Despertador cel Pepe"
      value_template: >
        {% if is_state('sensor.sm_g9650_2_next_alarm_2', 'unavailable') %}
        {{ 4102444800 | timestamp_local }}
        {% else %}
        {{ states('sensor.sm_g9650_2_next_alarm_2') }}
        {% endif %}
    siguiente_despertador:
      friendly_name: "Siguiente despertador"
      value_template: >
        {% if is_state('group.someone_home', 'not_home') %}
          {{ 4102444800 | timestamp_local }}
        {% else %}
          {% if ( is_state('person.brenda', 'home') and is_state('person.pepe', 'not_home') ) %}
            {{ states('sensor.despertador_brenda') }}
          {% endif %}
          {% if ( is_state('person.pepe', 'home') and is_state('person.brenda', 'not_home') ) %}
            {{ states('sensor.despertador_pepe') }}
          {% endif %}
          {% if ( is_state('person.brenda', 'home') and (as_timestamp(states('sensor.despertador_brenda')) < as_timestamp(states('sensor.despertador_pepe'))) ) %}
            {{ states('sensor.despertador_brenda') }}
          {% endif %}
          {% if ( is_state('person.pepe', 'home') and (as_timestamp(states('sensor.despertador_pepe')) < as_timestamp(states('sensor.despertador_brenda'))) ) %}
            {{ states('sensor.despertador_pepe') }}
          {% endif %}
        {% endif %}