##########################################################################################
###         Automatizaciones de aire acondicionado         ###############################
##########################################################################################

- alias: Encender AC
  description: 'Encender AC si hace calor y hay alguien en casa'
  trigger:
  - platform: template
    value_template: '{{states(''sensor.xiaomi_temp'')|float > 25.9 }}'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: climate.aire_acond_habitacion
      state: 'off'
    - condition: state
      entity_id: group.someone_home
      state: home
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.aire_acond_habitacion
      hvac_mode: heat_cool
  mode: single

##########################################################################################
##########################################################################################
##########################################################################################

- alias: Encender AC 2
  description: 'Encender AC cuando llegamos a casa si hace calor'
  trigger:
  - entity_id: group.someone_home
    platform: state
    to: home
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: climate.aire_acond_habitacion
      state: 'off'
    - condition: template
      value_template: '{{states(''sensor.xiaomi_temp'')|float > 25.9 }}'
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.aire_acond_habitacion
      hvac_mode: heat_cool
  mode: single

##########################################################################################
##########################################################################################
##########################################################################################  

- alias: Apagar AC 7am
  description: 'Apagar AC a las 7am si está encendido y a menos de 25 grados'
  trigger:
  - at: 07:00:00
    platform: time
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{states(''climate.aire_acond_habitacion'') != ''off''}}'
    - condition: template
      value_template: '{{states(''sensor.xiaomi_temp'')|float < 25.5 }}'
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.aire_acond_habitacion
      hvac_mode: 'off'   
  mode: single

##########################################################################################
##########################################################################################
##########################################################################################  

- alias: Apagar AC 4pm
  description: 'Apagar AC a las 4pm si está encendido y a menos de 25 grados'
  trigger:
  - at: '16:00:00'
    platform: time
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{states(''climate.aire_acond_habitacion'') != ''off''}}'
    - condition: template
      value_template: '{{states(''sensor.xiaomi_temp'')|float < 25.5 }}'
  action:
  - data:
      entity_id: climate.aire_acond_habitacion
      hvac_mode: 'off'
    service: climate.set_hvac_mode
  mode: single

